### PR TITLE
Prepends stanza

### PR DESCRIPTION
**Pull request by cliff-wakefield**
The stanza template places the prepends section below the Title of a stanza so it really isn't prepending it.

This swap the order of the elements of the stanza to move the prepend section to the top.

This is due to options you may specify apply to the next stanza, so if the options appear after the Title of the stanza it won't apply properly.

I didn't want to append the options to the preceding stanza.

### CODE REVIEW

**Comment by cliff-wakefield** [comment]
Not sure why the CI build failed?

Still new to this...

Change is simple enough.

**Comment by spacepants** [comment]
Code looks fine. Just need to [update the spec validation](https://github.com/spacepants/puppet-ezproxy/blob/master/spec/defines/stanza_spec.rb#L33) to match the new format.

**Comment by cliff-wakefield** [comment]
Ok done I believe, sorry still fairly new to building modules. Wasn't aware of this spec file.

**Comment by spacepants** [comment]
No worries. Merged, thanks.

**Pull request closed without merging**
